### ISSUE TITLE
Selenium-Standalone installation fails - `gulp serve` fails to start.

### ISSUE THREAD

**Issue by jennifer-dickinson** [udacity/exoplanet-explorer#20]
During npm install, the selenium-standalone installation fails and throws a reference error.
See below:

```
----------
selenium-standalone installation starting
----------

---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
to: C:\<redacted>\exoplanet-explorer\node_modules\wct-local\node_modules\selenium-standalone\.selenium\selenium-server\2.47.1-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_win32.zip
to: C:\<redacted>\exoplanet-explorer\node_modules\wct-local\node_modules\selenium-standalone\.selenium\chromedriver\2.18-x64-chromedriver
---
ie install:
from: http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.47.0.zip
to: C:<redacted>\exoplanet-explorer\node_modules\wct-local\node_modules\selenium-standalone\.selenium\iedriver\2.47.0-x64-IEDriverServer.exe
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\<redacted>\exoplanet-explorer\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\<redacted>\exoplanet-explorer\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\<redacted>\exoplanet-explorer\node_modules\fstream\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\<redacted>\exoplanet-explorer\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wct-local@1.7.1 (node_modules\wct-local):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wct-local@1.7.1 postinstall: `node scripts/postinstall.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Everything else executes without error, however when running `gulp serve`, gulp will not run and an error is thrown.

```
assert.js:373
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\<redacted>\exoplanet-explorer\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\<redacted>\exoplanet-explorer\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\<redacted>\exoplanet-explorer\gulpfile.js:179:6)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at execute (C:\<redacted>\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by jennifer-dickinson** [comment]
Fixed issue by uninstalling npm 12.8.0 and installing version 10.16.2.
