### ISSUE TITLE
Error when gulp serve

### ISSUE THREAD

**Issue by framled** [udacity/exoplanet-explorer#6]
Hi, I was watching your course at udacity about promise, and the xhr-start branch I get this error when I try to serve with gulp.
- vinyl version 0.5.3
- nodejs version 6.3.1
- npm version 3.10.3

```
[12:47:40] Using gulpfile ~/workspace/HTML/exoplanet-explorer/gulpfile.js
[12:47:40] Starting 'styles'...
[12:47:41] Starting 'elements'...
[12:47:41] Starting 'images'...
[12:47:41] Finished 'elements' after 189 ms
~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/vinyl/index.js:153
    if (!this.path) throw new Error('No path specified! Can not get relative.');
                    ^

Error: No path specified! Can not get relative.
    at File.Object.defineProperty.get (
~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/vinyl/index.js:153:27)
    at DestroyableTransform.saveFile [as _transform] (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/lib/dest/index.js:36:48)
    at DestroyableTransform.Transform._read (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at clearBuffer (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:316:5)
    at onwrite (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:274:7)
    at WritableState.onwrite (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at done (~/workspace/HTML/exoplanet-explorer/node_modules/vinyl-fs/lib/dest/writeContents/index.js:11:7)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

any solution for this?

**Comment by nikbabchenko** [comment]
Having the same issue(

**Comment by forbaz** [comment]
I have the same error, and i just added line
"vinyl": "0.3.0",
in package.json file, and run
npm install

**Comment by nikbabchenko** [comment]
Thank you bazgyrt!
It's so sad that contributors don't answer (

**Comment by elafrikano** [comment]
@bazgyrt your solution did not work for me! :(

**Comment by forbaz** [comment]
@elafrikano try this
`npm install vinyl@0.3.0 --save-dev`

**Comment by elafrikano** [comment]
@bazgyrt thanks you very much, it's worked!

**Comment by framled** [comment]
I will try this solution at weekend.
I hope this works
Thanks you guys.

**Comment by japrogramer** [comment]
@framled @nikbabchenko @bazgyrt @elafrikano 
```
alias npm-exec='PATH=$(npm bin):$PATH'
npm-exec gulp serve
```
edit: misread your issue,
assumed gulp was installed locally.

**Comment by framled** [comment]
this, works for me https://stackoverflow.com/a/40640752

**Comment by SalvadorP** [comment]
I had a different problem, related to svgo.yml file. 
This worked for me: https://github.com/svg/svgo/issues/622

**Comment by forbiddenvoid** [comment]
Unable to replicate this now. Feel free to open a new issue if it comes up again.
